version: 2.1
orbs:
  node: circleci/node@2.1.0
jobs:
  server-build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          app-dir: ./server
      - run:
          command: npm install
          working_directory: ./server
      - run:
          name: Running server tests
          command: npm test 
          working_directory: ./server
  client-build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          app-dir: ./client
      - run:
          command: npm install
          wokring_directory: ./client
      - run:
          name: Running client tests
          command: npm test 
          working_directory: ./client
  publish-docker:
    machine: true
    steps:
      - checkout
      - run: echo "$DOCKERPASS" | docker login -u "$DOCKERUSER" --password-stdin
      - run: 
          name: Docker publish server
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t dockeridwiktor/node-react-cicd-server:$TAG .
            docker push dockeridwiktor/node-react-cicd-server:$TAG
          working_directory: ./server
      - run: 
          name: Docker publish client
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t dockeridwiktor/node-react-cicd-client:$TAG .
            docker push dockeridwiktor/node-react-cicd-client:$TAG
          working_directory: ./client
        
workflows:
    build-and-test:
      jobs:
        - client-build-and-test:
          filters:
            branches:
              only:
                - master
        - server-build-and-test:
          filters:
            branches:
              only:
                - master
        - publish-docker:
            requires:
              - client-build-and-test
              - server-build-and-test
